### ISSUE TITLE
Icons missed

### ISSUE THREAD

**Issue by StreetStrider** [Marblr/mHUD#1]
Hello. I got an issue with mHUD. Fonts doesn't seem to be loaded, so every custom icon in UI missed.

In console I got the following error (colored red):

```
KeyValues Error: LoadFromBuffer: missing { in file 
(*CustomFontFiles*), (*15*), (*name*), (*russian*), (*range*), (*1*), (*offset*), (*4*), 
```

which is followed by debug message (colored white):

```
Hud element 'CHudItemAttributeTracker' doesn't have an entry 'ItemAttributeTracker' in scripts/HudLayout.res
```

I'm using TF2 with English language, so I can hear original voices. However, my Steam localized Russian, so TF2 follows this in texts/titles.

I've tried to investigate the reason. I've found this [suspicious chunk](https://github.com/Marblr/mHUD/blob/592af216d449893bf67458b4f62790950bdc7dbb/resource/ClientScheme.res#L10129-L10138). Here we have two of `"15"` key. I renamed 15 to 16 and reload hud. Issue still remains, but error now looks like this:

```
KeyValues Error: LoadFromBuffer: missing { in file 
(*CustomFontFiles*), (*16*), (*name*), (*russian*), (*range*), (*1*), (*offset*), (*4*), 
```

I believe key was just a misspelling, but real issue covers somewhere in this place.

**Comment by Marblr** [comment]
I fixed the clientscheme and hudlayout errors you mentioned. I can't say I'm sure how to support all languages without explicitly defining them in clientscheme, but they _should_ load regardless.

I suggest you try going to resource/fonts, selecting all the fonts, right clicking, and installing. If that does not fix it, I will look into a solution, but I can't guarantee a timely fix.

**Comment by StreetStrider** [comment]
I'll try master then. I'm not sure why this issue occur in first place, since I didn't had any issues with custom fonts previously in other HUDs.
If no success I'll install fonts globally, as you've adviced. Thanks.
